# Generated by Django 6.0.4 on 2026-04-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0004_storeuser_notif_promo_storeuser_notif_transac'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField()),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='store.storeuser')),
            ],
            options={
                'verbose_name': 'Device token',
                'verbose_name_plural': 'Device tokens',
                'unique_together': {('store_user', 'fcm_token')},
            },
        ),
    ]
