# Generated by Django 6.0.4 on 2026-04-27 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_mobile', '0001_initial'),
        ('sites_mgmt', '0014_mobile_app_release'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Message')),
                ('target', models.CharField(choices=[('all', 'Tous les clients'), ('site', 'Par site')], default='all', max_length=20, verbose_name='Cible')),
                ('notif_promo_only', models.BooleanField(default=True, help_text='Envoyer uniquement aux clients ayant activé les notifs promo', verbose_name='Promos seulement')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='Destinataires atteints')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('target_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_mgmt.hotspotsite', verbose_name='Site cible')),
            ],
            options={
                'verbose_name': 'Campagne push',
                'verbose_name_plural': 'Campagnes push',
                'ordering': ['-created_at'],
            },
        ),
    ]
