# Generated by Django 5.2.1 on 2026-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeuser_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash')], default='moncash', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
