# Generated by Django 6.0.4 on 2026-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_payment_method_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeuser',
            name='notif_promo',
            field=models.BooleanField(default=True, verbose_name='Notifications promos'),
        ),
        migrations.AddField(
            model_name='storeuser',
            name='notif_transac',
            field=models.BooleanField(default=True, verbose_name='Notifications transactions'),
        ),
    ]
