[build]
builder = "nixpacks"

[deploy]
startCommand = "sh -c 'python manage.py migrate && gunicorn bonnet.wsgi --bind 0.0.0.0:$PORT'"
healthcheckPath = "/accounts/login/"
restartPolicyType = "on_failure"
