# Generated by Django 6.0.4 on 2026-04-17 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ex: Forfait 12h', max_length=100, verbose_name='Label')),
                ('min_minutes', models.PositiveIntegerField(verbose_name='Durée min (minutes)')),
                ('max_minutes', models.PositiveIntegerField(verbose_name='Durée max (minutes)')),
                ('price_htg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (HTG)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tranche tarifaire',
                'verbose_name_plural': 'Tranches tarifaires',
                'ordering': ['min_minutes'],
            },
        ),
        migrations.CreateModel(
            name='HotspotSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('unifi_site_id', models.CharField(help_text='Identifiant interne UniFi (ex: default, site1)', max_length=50, unique=True, verbose_name='ID site UniFi')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(blank=True, limit_choices_to={'role': 'site_admin'}, related_name='managed_sites', to=settings.AUTH_USER_MODEL, verbose_name='Administrateurs assignés')),
            ],
            options={
                'verbose_name': 'Site Hotspot',
                'verbose_name_plural': 'Sites Hotspot',
                'ordering': ['name'],
            },
        ),
    ]
