# Generated by Django 5.2.1 on 2026-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotsite',
            name='auto_generate_vouchers',
            field=models.BooleanField(default=False, help_text='Génère 50 vouchers par forfait si le stock reste faible 36h après alerte.', verbose_name='Génération automatique'),
        ),
    ]
