# Generated by Django 5.2.1 on 2026-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0002_auto_generate_vouchers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text', models.CharField(blank=True, max_length=300, verbose_name='Texte du footer')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name='Logo 1')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name='Logo 2')),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
    ]
