# Generated by Django 5.2.1 on 2026-04-21 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0003_site_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hotspotsite',
            index=models.Index(fields=['is_active', 'name'], name='sites_mgmt__is_acti_6c9a3b_idx'),
        ),
    ]
