# Generated by Django 5.2.1 on 2026-04-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0013_hotspotsite_coords'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_file', models.FileField(blank=True, null=True, upload_to='mobile_app/', verbose_name='APK Android')),
                ('ios_file', models.FileField(blank=True, null=True, upload_to='mobile_app/', verbose_name='Fichier iOS')),
                ('version_name', models.CharField(blank=True, max_length=50, verbose_name='Version (ex: 1.0.0)')),
                ('release_notes', models.TextField(blank=True, verbose_name='Notes de mise à jour')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Version application mobile',
            },
        ),
        migrations.AlterField(
            model_name='vouchertier',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
    ]
