# Generated by Django 6.0.4 on 2026-04-17 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unifi_id', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('quota', models.PositiveIntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('revoked', 'Révoqué')], default='active', max_length=10)),
                ('price_htg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vouchers', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_logs', to='sites_mgmt.hotspotsite')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_mgmt.vouchertier')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'created_at'], name='vouchers_vo_site_id_8c2253_idx'), models.Index(fields=['status'], name='vouchers_vo_status_3eba33_idx')],
            },
        ),
    ]
