# Generated by Django 5.2.1 on 2026-04-21 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_mgmt', '0004_hotspotsite_sites_mgmt__is_acti_6c9a3b_idx'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='voucherlog',
            index=models.Index(fields=['created_by', 'created_at'], name='vouchers_vo_created_79ccfe_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherlog',
            index=models.Index(fields=['status', 'site'], name='vouchers_vo_status_4a3cf7_idx'),
        ),
    ]
