# Generated by Django 5.2.1 on 2026-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='auto_gen_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('stock_low', 'Stock faible'), ('monthly_report', 'Rapport mensuel'), ('auto_generated', 'Génération automatique')], max_length=30),
        ),
    ]
